apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-exchange-generator-service.fullname" . }}
  labels:
    {{- include "bank-exchange-generator-service.labels" . | nindent 4 }}
data:
  # Example: Generic key-value pairs from .Values.config
  # Note: We process database_url separately below using tpl
#  {{- range $key, $value := .Values.config }}
#  {{- if ne $key "database_url" }}
#  {{ $key }}: {{ $value | quote }}
#  {{- end }}
#  {{- end }}

  # Example: How Spring Boot might consume DB config (adjust keys as needed)
  # Ensure these keys match what your application expects.
  # Note: The values come from .Values.config which are set by the umbrella chart.
  # Use the 'tpl' function to render the database_url which contains Helm templating itself
  EXCHANGE_HOST: {{ tpl .Values.config.exchange_host . | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: {{ tpl .Values.config.keycloak_uri . | quote }}
  SPRING_KAFKA_BOOTSTRAP-SERVERS: {{ tpl .Values.config.kafka_server . | quote }}
  TOPIC_NAME: {{ tpl .Values.config.rates_topic_name . | quote }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: {{ tpl .Values.config.zipkin_endpoint . | quote }}

  # SPRING_DATASOURCE_PASSWORD would typically come from a secret, not this ConfigMap.

  # Example: Include other config defined in values.yaml
  # OTHER_CONFIG_PARAM: {{ .Values.config.some_other_config | quote }}