apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-exchange-generator-service.fullname" . }}
  labels:
    {{- include "bank-exchange-generator-service.labels" . | nindent 4 }}
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bank-exchange-generator-service.selectorLabels" . | nindent 4 }}
