elasticsearchHosts: "https://elasticsearch-master:9200"

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  type: LoadBalancer
  port: 8082

ingress:
  enabled: true
  className: "nginx" # Specify your ingress controller class
    #    annotations:
    #      kubernetes.io/ingress.class: nginx
    #      nginx.ingress.kubernetes.io/use-regex: "true"
    #      nginx.ingress.kubernetes.io/rewrite-target: /$2
    #    path: /exchange(/|$)(.*)
    #    pathType: ImplementationSpecific
  hosts:
    - host: kubernetes.docker.internal # Use global domain or specific
      paths:
        - path: /
          pathType: ImplementationSpecific