server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false
      discovery:
        prefer-ip-address: true

#  security:
#    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://keycloak:8080/realms/intershop
#        registration:
#          keycloak:
#            authorizationGrantType: client_credentials
#            provider: keycloak
#            client-id: intershop
#            client-secret: amrFoOMw2qhy50x126fYC2BJXETm6V1L
#            scope: profile
#            clientAuthenticationMethod: client_secret_post
    gateway:
      server:
        webmvc:
          routes:
            - id: cash-route
              uri: lb://cash
              predicates:
                - Path=/cash/**
              filters:
                - RewritePath=/cash/?(?<segment>.*), /$\{segment}
#                - TokenRelay=keycloak
            - id: account-route
              uri: lb://account
              predicates:
                - Path=/account/**
              filters:
                - RewritePath=/account/?(?<segment>.*), /$\{segment}
#                - TokenRelay=keycloak
            - id: blocker-route
              uri: lb://blocker
              predicates:
                - Path=/blocker/**
              filters:
                - RewritePath=/blocker/?(?<segment>.*), /$\{segment}
#                - TokenRelay=keycloak
            - id: exchange-route
              uri: lb://exchange
              predicates:
                - Path=/exchange/**
              filters:
                - RewritePath=/exchange/?(?<segment>.*), /$\{segment}
#                - TokenRelay=keycloak
            - id: notification-route
              uri: lb://notification
              predicates:
                - Path=/notification/**
              filters:
                - RewritePath=/notification/?(?<segment>.*), /$\{segment}
#                - TokenRelay=keycloak
            - id: transfer-route
              uri: lb://transfer
              predicates:
                - Path=/transfer/**
              filters:
                - RewritePath=/transfer/?(?<segment>.*), /$\{segment}
            - id: front-route
              uri: http://front:8079
              predicates:
                - Path=/**

