apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-account-service.fullname" . }}
  labels:
    {{- include "bank-account-service.labels" . | nindent 4 }}
data:
  # Example: Generic key-value pairs from .Values.config
  # Note: We process database_url separately below using tpl
  {{- range $key, $value := .Values.config }}
  {{- if eq $key "database_username" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

  # Example: How Spring Boot might consume DB config (adjust keys as needed)
  # Ensure these keys match what your application expects.
  # Note: The values come from .Values.config which are set by the umbrella chart.
  # Use the 'tpl' function to render the database_url which contains Helm templating itself
  SPRING_DATASOURCE_URL: {{ tpl .Values.config.database_url . | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.database_username | quote }}
  NOTIFICATION_HOST: {{ tpl .Values.config.notification_host . | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: {{ tpl .Values.config.keycloak_uri . | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: {{ tpl .Values.config.keycloak_uri . | quote }}
  SPRING_KAFKA_BOOTSTRAP-SERVERS: {{ tpl .Values.config.kafka_server . | quote }}
  TOPIC_NAME: {{ tpl .Values.config.notification_topic_name . | quote }}
  # SPRING_DATASOURCE_PASSWORD would typically come from a secret, not this ConfigMap.

  # Example: Include other config defined in values.yaml
  # OTHER_CONFIG_PARAM: {{ .Values.config.some_other_config | quote }}