apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bank-transfer-service.fullname" . }}
  labels:
    {{- include "bank-transfer-service.labels" . | nindent 4 }}
data:

  # Example: How Spring Boot might consume DB config (adjust keys as needed)
  # Ensure these keys match what your application expects.
  # Note: The values come from .Values.config which are set by the umbrella chart.
  # Use the 'tpl' function to render the database_url which contains Helm templating itself
  ACCOUNT_HOST: {{ tpl .Values.config.account_host . | quote }}
  BLOCKER_HOST: {{ tpl .Values.config.blocker_host . | quote }}
  NOTIFICATION_HOST: {{ tpl .Values.config.notification_host . | quote }}
  EXCHANGE_HOST: {{ tpl .Values.config.exchange_host . | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: {{ tpl .Values.config.keycloak_uri . | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: {{ tpl .Values.config.keycloak_uri . | quote }}
  SPRING_KAFKA_BOOTSTRAP-SERVERS: {{ tpl .Values.config.kafka_server . | quote }}
  TOPIC_NAME: {{ tpl .Values.config.notification_topic_name . | quote }}

  # Example: Include other config defined in values.yaml
  # OTHER_CONFIG_PARAM: {{ .Values.config.some_other_config | quote }}